apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: rates-shops-marriott-minio
  namespace: bsc
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 9
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - args:
                - 
                # - envconsul --once --consul-ssl --prefix=env-production-base --prefix=env/s3/seetransparent-bsc/rw --consul-addr=consul.pltp.us:8081 --consul-token=$CONSUL_TOKEN npm run bsc-pricing-export
              env:
                - name: NODE_OPTIONS
                  value: --max_old_space_size=8192
                - name: CONSUL_TOKEN
                  valueFrom:
                    secretKeyRef:
                      key: consul-token
                      name: consul-token
                      optional: false
                - name: DAY_OF_WEEK_FORMAT
                  value: "2"
                - name: OUTPUT_S3_PATH_FORMAT
                  value: "[s3://seetransparent-bsc/pricing/version-]YYYYMMDD[/]"
                - name: DELIVERY_FORMAT
                  value: "[BSC-]YYYYMMDD"
                - name: NUM_WORKERS
                  value: "5"
                - name: WORKER_INDEX
                  value: "1"
              image: seetransparent/crons:b32b321b60ec2549915cdf6bbecde9dda5025e13
              imagePullPolicy: Always
              name: bsc-pricing-export-minio-1
              resources: {}
              securityContext:
                allowPrivilegeEscalation: false
                capabilities: {}
                privileged: false
                readOnlyRootFilesystem: false
                runAsNonRoot: false
              stdin: true
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              tty: true
          dnsPolicy: ClusterFirst
          imagePullSecrets:
            - name: seetransparent
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: 30 1 * * 2
  successfulJobsHistoryLimit: 10
  suspend: false
